"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-datetime' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex_dev",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_dependency_module_importable(module_name):
    """Importing scitex-datetime's declared cross-package dependency must succeed."""
    # Arrange
    # Skip on the ROOT only — `importorskip` on the full path would
    # report a renamed submodule as merely absent (skip) instead of
    # failing loudly, which is the exact failure this gate exists to catch.
    pytest.importorskip(module_name.split(".")[0])

    # Act
    module = importlib.import_module(module_name)
    imported_name = getattr(module, "__name__", None)

    # Assert
    # The peer must self-report the same import name we asked for —
    # a renamed submodule would still import but be wired wrong.
    assert imported_name == module_name
